name: conexion_carga_app
description: "A new Flutter project."
publish_to: 'none'

# ============================================================
# CRÉDITOS / DEVELOPERS
# Proyecto: Conexión Carga
# Desarrollo: Daniel David Gaviria Zapata - Danilo Ramirez Osorio / Infinity Software 2025
# Contacto: infinitysoftware62@gmail.com
# ============================================================

version: 1.0.0+10

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.13.0
  flutter_easy_recaptcha_v2: ^0.1.0

  shared_preferences: ^2.2.2
  http: ^1.2.2
  intl: ^0.19.0

  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  share_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/docs/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon_V4.png"